name: Kotlin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install online-judge-tools
      run: |
        - pip3 install --upgrade pip
        - pip3 install online-judge-tools

    - name: Build
      run: ./gradlew build dokka
    - name: Download test cases
      run: ./gradlew downloadTestCase
    - name: Run test
      run: ./gradlew test
    - name: Deploy document
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build/dokka
